### ISSUE TITLE
Questions about the zoom meeting link of Q&A sessions

### ISSUE THREAD

**Issue by steve-yeung** [HKUST-Robotics-Team/Robotics-HKUST-2020-Tutorial#2]
Where are the Q&A sessions link and the tutorial videos, will they be emailed to us later or are there any other arrangement, any help is appreciated, thanks.

**Comment by kkdlau** [comment]
All notes and programs (if any) will be posted in this repo, and we will notify you via emails.
The zoom link will be sent out with the same arrangement.
